### ISSUE TITLE
Best practice with routing and views

### ISSUE THREAD

**Issue by RvZ** [flightphp/core#148]
Hi, I would like to know what is the best way to set up a website with different views and content.

My problem is that i can't use the variable from within a route outside the function and the other way around.I could use gobals and put all the render statements inside every route function i have.

But i think there is a better way. Is there? Can i find a example somewhere?

In my case Flight::render('layout/header', $header, 'header'); is outside all the routing functions but the $header has to be changed within the route functions

**Comment by jimlei** [comment]
I prefer this approach

flight -> route -> controller -> view

Using a template engine like Twig you can extend templates so you can render one file that extend a base layout which gives you the header/menu/footer as well.

**Comment by RvZ** [comment]
so you have the line: Flight::render('layout/header', $header, 'header'); in every controller? Is that the best option?

**Comment by jimlei** [comment]
Yeah I have a line like this in every method of every controller.

   Flight::view()->display('Thread/Single.twig', ['thread' => $thread]);

Since both the view file and params will change for a lot of the requests in a normal app it makes good sense.

Also its how its done in frameworks like Laravel, Symfony, Zend etc.
