### ISSUE TITLE
Regular expression in route

### ISSUE THREAD

**Issue by masakik** [flightphp/core#180]
Hi, thanks for the great framework. I´m trying to match a route to allow just lowercase chars using
Flight::route('GET /@var:/^[a-z]{1,}$/', function ($var) {
// do something
});
but seems not to work. I did not found documentation about regex syntax. This works on preg_match() php default.
What I´m doing wrong?
Masaki

**Comment by mikecao** [comment]
You don't need the full regex expression in routes, you can simply do:

``` php
Flight::route('/@var:[a-z]+', function($var){
  // Handle route
});
```

**Comment by masakik** [comment]
Thanks for the reply. It´s not supposed to but this is matching uppercase chars in my test case.

**Comment by webkenny** [comment]
Unless I am reading the code wrong, it looks like Flight is automatically defaulting to case insensitive. See [this line of code](https://github.com/mikecao/flight/blob/64d384ddffc5bc23ca641d313214974b8b0a5788/flight/net/Route.php#L124) in the routing for details. It's worth noting that this is probably a good thing since most web servers are not case sensitive with links.
