### ISSUE TITLE
Flight w/out .htaccess, is this possible?

### ISSUE THREAD

**Issue by mrsoto** [flightphp/core#205]
Hello.
  Is the a way to use Flight w/out setting rewrite rules?

Some thing like

`http://host/index.php?q=/my/request/endpoint`

Later

**Comment by mikecao** [comment]
Not currently, but it is something that I am planning to implement.

**Comment by fermino** [comment]
@mrsoto I think if you modify flight/net/Request.php, it could be possible. @mikecao, is it possible? xD

**Comment by pwFoo** [comment]
Without htaccess would be nice

**Comment by pwFoo** [comment]
Is there a update since issue is opened? 
I tested `/index.php/home` and it seems to work?  
```
Flight::route('/index.php/home', function(){
    echo 'Home Page!';
});
```

Not nice / clean urls, but best without htaccess? Or should some other features break by that "path"?

* update*
And how works the rewrite without append the path to index.php...?
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]
```
Most systems set the clean url path as query string?

**Comment by n0nag0n** [comment]
Is this still needed in 2023?

**Comment by krmu** [comment]
> Is this still needed in 2023?

No.

**Comment by eydun** [comment]
No
