### ISSUE TITLE
Multiple named parameters with regex failing.

### ISSUE THREAD

**Issue by wcatron** [flightphp/core#251]
This route `/account/clips/@id/analytics.@type:[a-z]+.@format:[a-z]+` fails to route with the URL: `account/clips/1234/analytics.views.xml`. The problem seems to be the regex for the named parameters doesn't know when to end. I can substitute the `.` for `/` and it works!
`/account/clips/@id/analytics.@type:[a-z]+/@format:[a-z]+` will route `account/clips/1234/analytics.views/xml`. I tried escaping the `.` but that didn't work. Is there an undocumented way to break the regex?

**Comment by mikecao** [comment]
Named parameters are supposed to be used per url segment. So something like this, `/account/clips/@id/analytics/@type/@format` would work. You can't chain them together like you're doing. If you really need that specific format, then you can just pass the entire segment and run your own regex:

``` php
Flight::route('/account/clips/@id/@page', function($id, $page) {
  // Run regex on $page parameter
});
```

It would probably be better performance-wise as well since it doesn't need to run a complex regex to match routes.

**Comment by wcatron** [comment]
Alright I can do that. I've been using .htaccess in the past so I'm use to very granular regex. Might be worth a note in the docs, I might have missed it though if it was. Thanks!

**Comment by victorcerutti** [comment]
I would love to be able to define regex for variables before routes.
For exemple, define @user:[a-z] and @page:[0-9]
And then have

```
flight::route('/profile/@user/@page', function($user, $page) {
  //match @user:[a-z] and @page:[0-9]
});
```

**Comment by wcatron** [comment]
That sounds cool to me, you should submit a feature request.
