### ISSUE TITLE
What is the practical use of the Mapping Method?

### ISSUE THREAD

**Issue by abbychau** [flightphp/core#272]
Whenever I have a visible class or function, I can always initialize and use them whenever I want.

When should we use extend a Flight::customName? Can you give a practical example to explain?

**Comment by tamtamchik** [comment]
It's used when you need to make your class act as **singleton**. 
Documentation: _By default, every time you load your class you will get a shared instance._

It's used for holding DB connection, logger, session store or whatever class you need to have the only single copy during your application workflow.

**Comment by abbychau** [comment]
I see. Thanks.

**Comment by tamtamchik** [comment]
Also, it gives you kind of abstraction over real implementation. 

For example, if you'll want to change logger from [KLogger](https://github.com/katzgrau/KLogger) to [monolog](https://github.com/Seldaek/monolog), you'll only have to change it once, in the definition method. And since they both implement same PSR-3 [LoggerInterface](https://github.com/php-fig/log) you won't need to change any line of your actual code.

**Comment by abbychau** [comment]
@tamtamchik Sure I got it. just like a public wrapper.
