### ISSUE TITLE
Flight::request()->data is empty

### ISSUE THREAD

**Issue by pcfutures** [flightphp/core#303]
When doing this:

    $request = Flight::request();
    $data = $request->data;

`$data` become an empty object, should it not be an array containing all the POST data?

Doing `$data = $request->data->$key` does work, however.

**Comment by ghost** [comment]
@pcfutures $data is not an array, it's an object of type `\flight\util\Collection` which has it's internal data object as a private attribute.

Since `\flight\util\Collection` implements the PHP internal `\Iterator` class, you can use the example found here to iterate through the collection: http://php.net/manual/en/class.iterator.php#96691

Alternatively, to get the value of a single index within the private `data` array stored inside of `\flight\util\Collection`, you can use `$object::getData($index)` or simply `$object->{$index}` though in my opinion the `getData()` method is a more elegant access method. If `$index` isn't set, it will return `null`, see `\flight\util\Collection::__get($key)` for more information.

**Comment by mikecao** [comment]
If you want to get the internal array, you need to do `$data = $request->data->getData();`.
