### ISSUE TITLE
Including Files and Using Constants

### ISSUE THREAD

**Issue by acefxlabs** [flightphp/core#307]
Hi I am developing an API application and i am having issues including file in Flight.
I wrote 
```
require '/flight/Flight.php';
define('APPKEY', '7823873268723671256126,);
```
And in my index 
```
require __DIR__.'/appCore/API/Constants.php';

Flight::route('GET /', function(){
    echo APPKEY;
});
```

And all i have been getting is error, 
I'm i calling the file wrongly or what am i doing wrong 

There is no doc on multiple files structure

Thanks

**Comment by ghost** [comment]
@acefxlabs in order to use flight, you need to call `Flight::start();` after registering your routes.

I would also verify that `__DIR__.'/appCore/API/Constants.php';` is in the location you think it is by running `var_dump(file_exists(__DIR__.'/appCore/API/Constants.php'));` in your index file, which should echo `true` if the file exists.

**Comment by mikecao** [comment]
You have to post what the error is. We can't help you without the error message.

**Comment by acefxlabs** [comment]
Thanks alot, Resolved
