### ISSUE TITLE
Compatibility issue with PHP 8.1-8.2

### ISSUE THREAD

**Issue by david-prv** [flightphp/core#481]
Hey everyone,

I just checked if the latest FlightPHP Version is ready to be used on an up-to-date
PHP system. And there is actually one error clashing with `PHP 8.1` and `PHP 8.2`.

PHP Codesniffers "PHPCompatibility Standard" explains:
```
FILE: .\flight-master\flight\Flight.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 75 | ERROR | Visibility for magic method __destruct must be public.
    |       | Found: private
----------------------------------------------------------------------
```

___________________________________

FlightPHP version used: `2.0.1`
How to reproduce:
```
git clone https://github.com/mikecao/flight.git
cd flight\flight
phpcs -p . --standard=PHPCompatibility --runtime-set testVersion 8.1 -v
```

**Comment by david-prv** [comment]
Is Flight abandoned?

**Comment by MisterAnmar** [comment]
> Is Flight abandoned?

Im wandering as well.,

**Comment by magikstm** [comment]
That doesn't seem to be an error with flightphp.

It seems to be an issue with PHP Codesniffers.

https://www.php.net/manual/en/language.oop5.magic.php

> Warning

All magic methods, with the exception of [__construct()](https://www.php.net/manual/en/language.oop5.decon.php#object.construct), [__destruct()](https://www.php.net/manual/en/language.oop5.decon.php#object.destruct), and [__clone()](https://www.php.net/manual/en/language.oop5.cloning.php#object.clone), must be declared as public, otherwise an E_WARNING is emitted. Prior to PHP 8.0.0, no diagnostic was emitted for the magic methods [__sleep()](https://www.php.net/manual/en/language.oop5.magic.php#object.sleep), [__wakeup()](https://www.php.net/manual/en/language.oop5.magic.php#object.wakeup), [__serialize()](https://www.php.net/manual/en/language.oop5.magic.php#object.serialize), [__unserialize()](https://www.php.net/manual/en/language.oop5.magic.php#object.unserialize), and [__set_state()](https://www.php.net/manual/en/language.oop5.magic.php#object.set-state).

**Comment by magikstm** [comment]
Reported: https://github.com/PHPCompatibility/PHPCompatibility/issues/1542

Fixed: https://github.com/PHPCompatibility/PHPCompatibility/pull/1543

**Comment by magikstm** [comment]
> Is Flight abandoned?

I'm not the author of flightphp, but I've followed it for a few years. I'll share my thoughts on it's status.

It isn't abandoned, but it's not in active development.

**Comment by krmu** [comment]
Tested with PHP 8.3.1. works fine.
Can be closed. @n0nag0n

**Comment by n0nag0n** [comment]
Thank you @krmu! That was on my list!
