### ISSUE TITLE
Simplify PHP version constraint

### ISSUE THREAD

**Issue by fadrian06** [flightphp/core#587]
Reading the composer documentation and testing it with some tools, it turns out that the operator >= 7.4 It would be a simplified way to the PHP version constraints that currently exist both in composer.json, in the packagist info, and in the README badge

https://getcomposer.org/doc/articles/versions.md#version-range

Tool: https://semver.madewithlove.com/?package=php&constraint=%3E%3D7.4

![Screenshot_20240509-022705.png](https://github.com/flightphp/core/assets/109766973/87fd197e-a4c7-4d2a-bee1-205e74916b5a)

**Comment by vlakoff** [comment]
Generally speaking, the `>=` operator should be avoided, because it is recommended to always put an upper bound, at least on the next major version (i.e. the first number).

I would recommend `^7.4|^8.0` instead. So the previous code, but removing the `^8.1|^8.2|^8.3` part that was redundant.

* `^7.4`: >=7.4 and < 8.0
* `^8.0`: >=8.0 and < 9.0

This way we support PHP >= 7.4, but we prevent running on an hypothetical future PHP 9.0, as it would certainly require updates in Flight to work.

**Comment by fadrian06** [comment]
I guess you're right, even if we guarantee that flight will always support latest and lts versions... for older versions it might break

**Comment by fadrian06** [comment]
I guess you're right, even if we guarantee that flight will always support latest and lts versions... for older versions it might break

**Comment by fadrian06** [comment]
Although honestly, if I had php 9 and flight was already in version 6 for example...why would it cross my mind to download an old version?

**Comment by fadrian06** [comment]
Although honestly, if I had php 9 and flight was already in version 6 for example...why would it cross my mind to download an old version?
