### ISSUE TITLE
Route Groups strange behavior

### ISSUE THREAD

**Issue by abda11ah** [flightphp/core#610]
**Describe the bug**

**To Reproduce**
1. Here's some sample code : 
```
Flight::group('/profile', function () {
    $uc = new UserController();

    Flight::route('GET /edit', function () use ($uc) {
        AuthMiddleware::handle();
        $uc->edit();
        Flight::render('profile/edit', [], 'content');
        Flight::render('layout');
    });

    Flight::route('GET /@id', function ($id) use ($uc) {
        AuthMiddleware::handle();
        $uc->view($id);
        Flight::render('profile/view', [], 'content');
        Flight::render('layout');
    });
 });
```
In this case :
GET /profile/4 : works
GET /profile/edit : works

When i invert the position of the 2 sub routes like this :

```
Flight::group('/profile', function () {
    $uc = new UserController();

    Flight::route('GET /@id', function ($id) use ($uc) {
        AuthMiddleware::handle();
        $uc->view($id);
        Flight::render('profile/view', [], 'content');
        Flight::render('layout');
    });
    
    Flight::route('GET /edit', function () use ($uc) {
        AuthMiddleware::handle();
        $uc->edit();
        Flight::render('profile/edit', [], 'content');
        Flight::render('layout');
    });
 });
```

GET /profile/4 : works
GET /profile/edit : returns 404 error

**Expected behavior**
same behavior in the 2 cases.

**Environment (please complete the following information):**
 - OS: Fedora linux 41
 - Browser Firefox latest
 - PHP Version 8.3.14
 - Flight Version 3.13

**Comment by kuopassa** [comment]
Probably because `@id` covers also `edit` as a valid value. Maybe you could try to limit `@id` like: `@id:[0-9]`

**Comment by n0nag0n** [comment]
@kuopassa is right on the money! Because `@id` is at the end of the route and it's a variable (and it's not specifying that it's only an int) it assumes that anything that's passed into that route is valid. So if you went to your code on the `/edit` route you'll notice that it will get passed to the `@id` route and the `$id` variable will actually say `'edit'`. 

The way to structure your routes in Flight (and other frameworks too) is specific routes up top and more general routes on the bottom.
